Python 3 compatibility (closes #24)
DataBiosphere/dos-dss-lambda pull request #25
Opened 2018-08-15 18:37 UTC by natanlao

As we're waiting for a test suite, I independently confirmed that these changes don't break anything. (That said, the `_scroll_id` and `search_after` key discrepancy still exists.)

2018-08-15 18:40 UTC, natanlao commented
This PR implements Python 3 compatibility while maintaining Python 2 compatibility.

2018-08-24 21:59 UTC, mjkrause commented
The sentence _As we're waiting for a test suite, I independently confirmed that these changes don't break anything._ is difficult to comprehend. 

I'm not sure what you mean by "waiting for...", and "independent ..." from what, and what changes?

2018-08-24 22:18 UTC, natanlao commented
@mjkrause Apologies, let me clarify: I'm working on introducing a standardized test suite for all of our DOS lambdas (TLP-492). This is the same one I've discussed at stand up. 

Since dos-dss-lambda currently lacks tests, I had to manually verify that the lambda worked as intended despite the changes made in this PR.

2018-08-24 22:19 UTC, mjkrause requested changes

2018-08-24 22:19 UTC, mjkrause commented on app.py
> +    data_object['urls'] = [{'url': x} for x in reference_json['url']]
I like that you turned the lambdas into list comprehensions - those are also somewhat cryptic, but a breeze compared to lambdas (my personal opinion).

2018-08-24 22:19 UTC, mjkrause commented on app.py
> +        response['data_bundles'] = list(map(dss_list_bundle_to_dos, res.json()['results']))
Is the `list` command needed for Python 3? How do you ensure Python 2 compatibility? Or would that raise an exception?

2018-08-25 00:40 UTC, mjkrause commented on app.py
> +        response['data_bundles'] = list(map(dss_list_bundle_to_dos, res.json()['results']))
Hi Natan, thanks for taking the time to answer my comments / questions. In know you mentioned your work and actions during standup, but I see commits and PRs more as a form of record keeping so we can revisit it later and know what was done and why.

2018-08-25 00:40 UTC, mjkrause approved these changes

2018-08-27 16:29 UTC, natanlao commented
Thank you for the review, @mjkrause!

2018-08-27 16:30 UTC, merged